config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :chatrooms

  root 'chatrooms#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
    has_many :messages
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chatroom

  # def time_zone

  # end
end

app/models/user.rb
class User < ApplicationRecord
    validates :username, uniqueness: true


    def self.randomize
    first_part = 'ChatMember'
    second_part = ['A', 'B', 'C', 'D']
    third_part = rand(1..20)
    username = "#{first_part}#{second_part.sample}#{third_part}"
    create(username: username)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # before_action :reset_session
    helper_method :current_user
    # helper_method :hello_user

    def current_user
        return @current_user if @current_user.present?

        if session[:user_id].present?
            @current_user  = User.find(session[:user_id])
        else
            puts "welcome user"
            @current_user = User.randomize
            session[:user_id] = @current_user.id
            puts "hello user"
            @message = Message.new()
            @message.user_id = @current_user.id
            @message.chatroom_id = 1
            @message.chat = "Welcome New User!" 
            @message.user = current_user
            @message.save 
            @current_user
        end

        @current_user
    end

    # def hello_user
    #     puts "hello user"
    #     @message = Message.new(:chat, :user_id, :chatroom_id)
    #     @message.user = current_user
    #     @message.save 
    # end

    def destroy
        session.delete :user_id
    end

    private

    def message_params
        params.require(:message).permit(:chat, :user_id, :chatroom_id)
    end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  before_action :set_chatroom, only: %i[ show edit update destroy ]

  # GET /chatrooms or /chatrooms.json
  def index
    @chatrooms = Chatroom.all
  end

  # GET /chatrooms/1 or /chatrooms/1.json
  def show
    @chatrooms = Chatroom.all
    render 'index'
  end
  # GET /chatrooms/new
  def new
    @chatroom = Chatroom.new
  end

  # GET /chatrooms/1/edit
  def edit
  end

  # POST /chatrooms or /chatrooms.json
  def create
    @chatroom = Chatroom.new(chatroom_params)

    respond_to do |format|
      if @chatroom.save
        format.html { redirect_to chatroom_url(@chatroom), notice: "Chatroom was successfully created." }
        format.json { render :show, status: :created, location: @chatroom }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chatrooms/1 or /chatrooms/1.json
  def update
    respond_to do |format|
      if @chatroom.update(chatroom_params)
        format.html { redirect_to chatroom_url(@chatroom), notice: "Chatroom was successfully updated." }
        format.json { render :show, status: :ok, location: @chatroom }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chatrooms/1 or /chatrooms/1.json
  def destroy
    @chatroom.destroy

    respond_to do |format|
      format.html { redirect_to chatrooms_url, notice: "Chatroom was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chatroom
      @chatroom = Chatroom.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def chatroom_params
      params.require(:chatroom).permit(:name)
    end
end

  

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: %i[ show edit update destroy ]

  # GET /messages or /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1 or /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages or /messages.json
  def create
    @message = Message.new(message_params)
    @message.user = current_user
    @message.save 
    SendMessageJob.perform_later(@message)  
   

  end

  # PATCH/PUT /messages/1 or /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to message_url(@message), notice: "Message was successfully updated." }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1 or /messages/1.json
  def destroy
    @message.destroy

    respond_to do |format|
      format.html { redirect_to messages_url, notice: "Message was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def message_params
      params.require(:message).permit(:chat, :user_id, :chatroom_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/chatrooms/_chatroom.html.erb
<div id="<%= dom_id chatroom %>">
  <p>
    <strong>Name:</strong>
    <%= chatroom.name %>
  </p>

</div>

app/views/chatrooms/_form.html.erb
<%= form_with(model: chatroom, class: 'form-inline') do |form| %>
  <% if chatroom.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(chatroom.errors.count, "error") %> prohibited this chatroom from being saved:</h2>
      <ul>
        <% chatroom.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class: 'form-control mt-2' %>
  </div>
  <div class='submit'>
    <%= form.submit 'Create Chatroom', class: 'btn btn-info btn-block col-12 mt-2' %>
  </div>
<% end %>

app/views/chatrooms/edit.html.erb
<h1>Editing chatroom</h1>

<%= render "form", chatroom: @chatroom %>

<br>

<div>
  <%= link_to "Show this chatroom", @chatroom %> |
  <%= link_to "Back to chatrooms", chatrooms_path %>
</div>

app/views/chatrooms/index.html.erb
<p style="color: green"><%= notice %></p> 
<div class="container-fluid">
  <div class="row">
    <div class="col-2">
      <%= render 'form', chatroom: Chatroom.new %>
      <hr>
      <% @chatrooms.each do |chatroom| %>
        <%= link_to chatroom do %>
          <div class="card mb-2">
            <div class="card-body">
              <%= chatroom.name %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class = 'col-9'>
      <% if @chatroom.present? %>
        <div class="chat-room">
          <nav class="navbar navbar-light bg-info mb-2">
            <span class="navbar-brand" href="#"><%= @chatroom.name %></span>
            <ul class='navbar-nav'>
              <li class='nav-item'>Welcome, 
                <%= current_user.username %>
              </li>
            </ul>
          </nav>
          <div id="messages">
            <% @chatroom.messages.each do |message| %>
              <%= render 'messages/message', message: message %>
            <% end %>
          </div>
          <div class = "message-area">
            <%= render 'messages/form', message: Message.new, chatroom: @chatroom %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/chatrooms/new.html.erb
<h1>New chatroom</h1>

<%= render "form", chatroom: @chatroom %>

<br>

<div>
  <%= link_to "Back to chatrooms", chatrooms_path %>
</div>

app/views/chatrooms/show.html.erb
<%= render @chatroom %>

<div>
  <%= link_to "Edit this chatroom", edit_chatroom_path(@chatroom) %> |
  <%= link_to "Back to chatrooms", chatrooms_path %>

  <%= button_to "Delete", @chatroom, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LetsChat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" 
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <%= stylesheet_link_tag "style", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_with(model: message, class: 'form-inline') do |form| %>
  <% if message.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <% message.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.text_area :chat, placeholder: 'Enter message..', class: 'form-control mb-2' %>
  </div>


 
    <%= form.hidden_field :chatroom_id, value: chatroom.id %>


  <div>
    <%= form.submit 'Send', class: 'btn btn-info'%>
  </div>
<% end %>

app/views/messages/_message.html.erb
 <div class = "message mb-2 <%= 'me' if message.user == current_user%>">
                <div class="chat-container">
                  <div class = "chat">
                    <%= message.chat %>
                  </div>
                  <div class="user">
                    <%= message.user.username %>
                    <br>
                     <%= time = message.created_at
                          time.strftime("%H:%M:%S")
                      %>
                  </div>
                </div>
              </div>

             

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render "form", message: @message %>

<br>

<div>
  <%= link_to "Show this message", @message %> |
  <%= link_to "Back to messages", messages_path %>
</div>

app/views/messages/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Messages</h1>

<div id="messages">
  <% @messages.each do |message| %>
    <%= render message %>
    <p>
      <%= link_to "Show this message", message %>
    </p>
  <% end %>
</div>

<%= link_to "New message", new_message_path %>

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render "form", message: @message %>

<br>

<div>
  <%= link_to "Back to messages", messages_path %>
</div>

app/views/messages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @message %>

<div>
  <%= link_to "Edit this message", edit_message_path(@message) %> |
  <%= link_to "Back to messages", messages_path %>

  <%= button_to "Destroy this message", @message, method: :delete %>
</div>